#default: &default
#  adapter: postgresql
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: db/react
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sa
  host: localhost
  password: pass

test:
  adapter: postgresql
  encoding: unicode
  database: db/react
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: sa
  host: localhost
  password: pass

production:
  adapter: postgresql
  encoding: unicode
  database: db/react
  host: localhost
  password: 
